/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CompiladoresHoc5;

import static CompiladoresHoc5.EnumBLTIN.ABS;
import static CompiladoresHoc5.EnumBLTIN.SIN;
import static CompiladoresHoc5.EnumInstrMaq.ASSIGN;
import static CompiladoresHoc5.EnumInstrMaq.CONSTPUSH;
import static CompiladoresHoc5.EnumInstrMaq.VARPUSH;
import static CompiladoresHoc5.EnumTipoSymbol.VAR;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.Reader;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.util.Iterator;
import java_cup.runtime.Symbol;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jesus
 */
public class formHoc5 extends javax.swing.JFrame {
    AnalizadorSintactico Sintac;
    /**
     * Creates new form formHoc5
     */
    public formHoc5() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        textoAAnalizar = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaTokens = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtResultSintactico = new javax.swing.JTextArea();
        btnAnalizadorLex = new javax.swing.JButton();
        btnAnalizSintactico = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableCodigo = new javax.swing.JTable();
        ejecutarCodigo = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textoAAnalizar.setColumns(20);
        textoAAnalizar.setRows(5);
        jScrollPane1.setViewportView(textoAAnalizar);

        txtAreaTokens.setEditable(false);
        txtAreaTokens.setColumns(20);
        txtAreaTokens.setRows(5);
        jScrollPane2.setViewportView(txtAreaTokens);

        txtResultSintactico.setEditable(false);
        txtResultSintactico.setColumns(20);
        txtResultSintactico.setRows(5);
        jScrollPane3.setViewportView(txtResultSintactico);

        btnAnalizadorLex.setText("Analizar Léxicamente");
        btnAnalizadorLex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalizadorLexActionPerformed(evt);
            }
        });

        btnAnalizSintactico.setText("Análisis Sintáctico");
        btnAnalizSintactico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalizSintacticoActionPerformed(evt);
            }
        });

        jLabel1.setText("Expresión a Analizar");

        jTableCodigo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NUM_INSTRUCT", "INST-SYMB-FUNC", "NAME", "VAL", "FUNCIÓN"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTableCodigo);

        ejecutarCodigo.setText("Ejecutar Código");
        ejecutarCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejecutarCodigoActionPerformed(evt);
            }
        });

        txtResultado.setEditable(false);
        txtResultado.setColumns(20);
        txtResultado.setRows(5);
        jScrollPane6.setViewportView(txtResultado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnAnalizadorLex)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 404, Short.MAX_VALUE))
                                    .addComponent(jScrollPane2)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAnalizSintactico)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ejecutarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                        .addGap(31, 31, 31))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnalizadorLex)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnalizSintactico)
                    .addComponent(ejecutarCodigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnalizadorLexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalizadorLexActionPerformed
        // TODO add your handling code here:
        Symbol simb;
        String Lexema = new String();
        String cadAux = new String();
        File archEntrada = new File("archEntrada.txt");
        PrintWriter escribir;
        txtAreaTokens.setText("");
        
        try{
            escribir = new PrintWriter(archEntrada);
            escribir.print(textoAAnalizar.getText());
            escribir.close();
            //System.out.println("Obtiene texto a analizar");
        }catch(FileNotFoundException ex){
            //Logger.getLogger(formHoc5.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try{
            Reader lector;
            lector = new FileReader("archEntrada.txt");
            
            AnalizadorLexico AnalizLexico = new AnalizadorLexico(lector);
            AnalizLexico.maqHoc = new MaquinaHoc4();
            AnalizLexico.maqHoc.AreaResult = txtResultado;
            //System.out.println("Lee aRCHENTRADA");
            do{
                simb = AnalizLexico.next_token();
                cadAux = Integer.toString(simb.sym);
                Lexema = AnalizLexico.yytext();
                
                if(simb.sym==AnalizadorSintacticoSym.EOF){
                    cadAux = "Token: " + cadAux + "\tIdentToken: FIN \n";
                }else{
                    switch(simb.sym){
                        case AnalizadorSintacticoSym.SEMIC:
                            cadAux = "Token: " + cadAux + "\tIdentToken: SEMIC\t Lexema: " + Lexema + "\n";
                            break;
                        case AnalizadorSintacticoSym.NUM:
                            cadAux = "Token: " + cadAux + "\tIdentToken: NUM\t Lexema: " + Lexema + "\n";
                            break;
                        case AnalizadorSintacticoSym.CONST_PRED:
                            cadAux = "Token: " + cadAux + "\tIdentToken: CONST_PRED\t Lexema: " + Lexema + "\n";
                            break;
                        case AnalizadorSintacticoSym.BLTIN:
                            cadAux = "Token: " + cadAux + "\tIdentToken: BLTIN\t Lexema: " + Lexema + "\n";
                            break;
                        case AnalizadorSintacticoSym.MENOSUNARIO:
                            cadAux = "Token: " + cadAux + "\tIdentToken: MENOSUNARIO\t Lexema: " + Lexema + "\n";
                            break;
                        case AnalizadorSintacticoSym.OpAsig:
                            cadAux = "Token: " + cadAux + "\tIdentToken: OpAsig\t Lexema: " + Lexema + "\n";
                            break;
                        case AnalizadorSintacticoSym.OpDiv:
                            cadAux = "Token: " + cadAux + "\tIdentToken: OpDiv\t Lexema: " + Lexema + "\n";
                            break;
                        case AnalizadorSintacticoSym.OpPotencia:
                            cadAux = "Token: " + cadAux + "\tIdentToken: OpPotencia\t Lexema: " + Lexema + "\n";
                            break;
                        case AnalizadorSintacticoSym.OpProd:
                            cadAux = "Token: " + cadAux + "\tIdentToken: OpProd\t Lexema: " + Lexema + "\n";
                            break;
                        case AnalizadorSintacticoSym.OpResta:
                            cadAux = "Token: " + cadAux + "\tIdentToken: OpResta\t Lexema: " + Lexema + "\n";
                            break;
                        case AnalizadorSintacticoSym.OpSuma:
                            cadAux = "Token: " + cadAux + "\tIdentToken: OpSuma\t Lexema: " + Lexema + "\n";
                            break;
                        case AnalizadorSintacticoSym.ParDer:
                            cadAux = "Token: " + cadAux + "\tIdentToken: ParDer\t Lexema: " + Lexema + "\n";
                            break;
                        case AnalizadorSintacticoSym.ParIzq:
                            cadAux = "Token: " + cadAux + "\tIdentToken: ParIzq\t Lexema: " + Lexema + "\n";
                            break;   
                        case AnalizadorSintacticoSym.VAR:
                            cadAux = "Token: " + cadAux + "\tIdentToken: VAR\t Lexema: " + Lexema + "\n";
                            break; 
                            
                        /*Nuevos casos*/    
                        case AnalizadorSintacticoSym.AND:
                            cadAux = "Token: " + cadAux + "\tIdentToken: AND\t Lexema: " + Lexema + "\n";
                            break;
                        case AnalizadorSintacticoSym.OR:
                            cadAux = "Token: " + cadAux + "\tIdentToken: OR\t Lexema: " + Lexema + "\n";
                            break;
                        case AnalizadorSintacticoSym.EQ:
                            cadAux = "Token: " + cadAux + "\tIdentToken: EQ\t Lexema: " + Lexema + "\n";
                            break;
                        case AnalizadorSintacticoSym.NE:
                            cadAux = "Token: " + cadAux + "\tIdentToken: NE\t Lexema: " + Lexema + "\n";
                            break;    
                        case AnalizadorSintacticoSym.NOT:
                            cadAux = "Token: " + cadAux + "\tIdentToken: NOT\t Lexema: " + Lexema + "\n";
                        break;
                        case AnalizadorSintacticoSym.GT:
                            cadAux = "Token: " + cadAux + "\tIdentToken: GT\t Lexema: " + Lexema + "\n";
                            break;
                        case AnalizadorSintacticoSym.GE:
                            cadAux = "Token: " + cadAux + "\tIdentToken: GE\t Lexema: " + Lexema + "\n";
                            break;
                        case AnalizadorSintacticoSym.LT:
                            cadAux = "Token: " + cadAux + "\tIdentToken: LT\t Lexema: " + Lexema + "\n";
                            break;
                        case AnalizadorSintacticoSym.LE:
                            cadAux = "Token: " + cadAux + "\tIdentToken: LE\t Lexema: " + Lexema + "\n";
                            break;
                        case AnalizadorSintacticoSym.LlaveDer:
                            cadAux = "Token: " + cadAux + "\tIdentToken: LlaveDer\t Lexema: " + Lexema + "\n";
                            break;    
                        case AnalizadorSintacticoSym.LlaveIzq:
                            cadAux = "Token: " + cadAux + "\tIdentToken: LLaveIzq\t Lexema: " + Lexema + "\n";
                            break;
                        case AnalizadorSintacticoSym.IF:
                            cadAux = "Token: " + cadAux + "\tIdentToken: IF\t Lexema: " + Lexema + "\n";
                            break;
                        case AnalizadorSintacticoSym.ELSE:
                            cadAux = "Token: " + cadAux + "\tIdentToken: ELSE\t Lexema: " + Lexema + "\n";
                            break;
                        case AnalizadorSintacticoSym.WHILE:
                            cadAux = "Token: " + cadAux + "\tIdentToken: WHILE\t Lexema: " + Lexema + "\n";
                            break; 
                        case AnalizadorSintacticoSym.PRINT:
                            cadAux = "Token: " + cadAux + "\tIdentToken: PRINT\t Lexema: " + Lexema + "\n";
                            break;    
                        default:
                            cadAux = "Token: " + cadAux + "\tIdentToken: OTRO\t Lexema: " + Lexema + "\n";
                    }
                }
                
                txtAreaTokens.append(cadAux);
                
            }while(simb.sym!=AnalizadorSintacticoSym.EOF);
        
        }catch(IOException ex){
            txtAreaTokens.append("CatchError \n");
            //Logger.getLogger(formHoc5.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        txtAreaTokens.repaint();
    }//GEN-LAST:event_btnAnalizadorLexActionPerformed

    private void btnAnalizSintacticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalizSintacticoActionPerformed
        // TODO add your handling code here:
        String cadAux = new String();
        
        String cadInst = new String();
        String name = new String();
        String valor = new String();
        String ptrFunc = new String();
        Object os[] = new Object[5];
        
        DefaultTableModel modeloTabla = (DefaultTableModel) jTableCodigo.getModel();
        InstrucPrograma instruc;
        AnalizadorLexico lexic =  null;
        
        txtResultSintactico.setText("");
        
        try{
            lexic = new AnalizadorLexico(new FileReader("archEntrada.txt"));
            System.out.println("Lee archEntrada");
        }catch(FileNotFoundException ex){
            System.out.println("Error al leer archEntrada");
        }
        
        modeloTabla.setRowCount(0);
        
        try{
            Sintac = new AnalizadorSintactico(lexic);
            Sintac.frmInterfaz = this;
            Sintac.maquinaHoc4 = new MaquinaHoc4();
            Sintac.maquinaHoc4.AreaResult = txtResultado;
            lexic.maqHoc = Sintac.maquinaHoc4;
            
            SymbolHoc s;
            Iterator it = lexic.maqHoc.TabSimb.ListaSimbolos.iterator();
            
            while(it.hasNext()){
                s = (SymbolHoc) it.next();
                cadAux = "--------------------------------\n"
                        +" Symbol: " + s.name + "\n" +
                         "----------------------------------";
                txtAreaTokens.append(cadAux);
            }
            
            try{
                Object result = Sintac.parse().value;
                
                InstrucPrograma ins2 = new InstrucPrograma();
                ins2.TipInstr = EnumTipoInstr.INSTRUC;
                ins2.Instruc = EnumInstrMaq.STOP;
                
                Sintac.maquinaHoc4.code(ins2);
            }catch(Exception ex){
            }
            
            txtResultSintactico.append("\n FIN DEL ANÁLISIS SINTÁCTICO");
            
            for(int i=0; i<Sintac.maquinaHoc4.progp; i++){
                instruc = Sintac.maquinaHoc4.Prog[i];
                
                cadAux = "----ERROR-----";
                
                cadInst = "";
                name = "";
                valor = "";
                ptrFunc = "";
                
                switch(instruc.TipInstr){
                    case INSTRUC:
                        switch(instruc.Instruc){
                            case ADD:
                                cadAux = "instruc ADD";
                                cadInst = "ADD";
                                break;
                            case ASSIGN:
                                cadAux = "instruc ASSIGN";
                                cadInst = "ASSIGN";
                                break;
                            case BLTIN:
                                cadAux = "instruc BLTIN";
                                cadInst = "BLTIN";
                                break;
                            case CONSTPUSH:
                                cadAux = "instruc CONSTPUSH";
                                cadInst = "CONSTPUSH";
                                break;
                            case VARPUSH:
                                cadAux = "instruc VARPUSH";
                                cadInst = "VARPUSH";
                                break;
                            case DIV:
                                cadAux = "instruc DIV";
                                cadInst = "DIV";
                                break;
                            case EVAL:
                                cadAux = "instruc EVAL";
                                cadInst = "EVAL";
                                break;
                            case MUL:
                                cadAux = "instruc MUL";
                                cadInst = "MUL";
                                break;
                            case NEGATE:
                                cadAux = "instruc NEGATE";
                                cadInst = "NEGATE";
                                break;
                            case POWER:
                                cadAux = "instruc POWER";
                                cadInst = "POWER";
                                break; 
                            case PRINT:
                                cadAux = "instruc PRINT";
                                cadInst = "PRINT";
                                break;     
                            case STOP:
                                cadAux = "instruc STOP";
                                cadInst = "STOP";
                                break;   
                            case SUB:
                                cadAux = "instruc SUB";
                                cadInst = "SUB";
                                break;
                            case AND:
                                cadAux = "instruc AND";
                                cadInst = "AND";
                                break; 
                            case OR:
                                cadAux = "instruc OR";
                                cadInst = "OR";
                                break; 
                            case NOT:
                                cadAux = "instruc NOT";
                                cadInst = "NOT";
                                break;
                            case GE:
                                cadAux = "instruc GE";
                                cadInst = "GE";
                                break; 
                            case GT:
                                cadAux = "instruc GT";
                                cadInst = "GT";
                                break; 
                            case LE:
                                cadAux = "instruc LE";
                                cadInst = "LE";
                                break;
                            case LT:
                                cadAux = "instruc LT";
                                cadInst = "LT";
                                break;
                            case NE:
                                cadAux = "instruc NE";
                                cadInst = "NE";
                                break;
                            case EQ:
                                cadAux = "instruc EQ";
                                cadInst = "EQ";
                                break; 
                            case IFCODE:
                                cadAux = "instruc IFCODE";
                                cadInst = "IFCODE";
                                break; 
                            case WHILECODE:
                                cadAux = "instruc WHILECODE";
                                cadInst = "WHILECODE";
                                break; 
                        }
                        cadAux += "\n";
                        txtAreaTokens.append(cadAux);
                        break;
                    
                    case BLTIN:
                        cadInst = "FruncPredef";
                        
                        switch(instruc.Func_BLTIN){
                            case ABS:
                                cadAux = "bltin ABS";
                                name = "abs";
                                ptrFunc = "ABS";
                                break; 
                            case ATAN:
                                cadAux = "bltin ATAN";
                                name = "atan";
                                ptrFunc = "ATAN";
                                break;
                            case SIN:
                                cadAux = "bltin SIN";
                                name = "sin";
                                ptrFunc = "SIN";
                                break;
                            case COS:
                                cadAux = "bltin COS";
                                name = "cos";
                                ptrFunc = "COS";
                                break; 
                            case LOG:
                                cadAux = "bltin LOG";
                                name = "log";
                                ptrFunc = "LOG";
                                break;
                            case LOG10:
                                cadAux = "bltin LOG10";
                                name = "log10";
                                ptrFunc = "LOG10";
                                break;
                            case EXP:
                                cadAux = "bltin EXP";
                                name = "exp";
                                ptrFunc = "EXP";
                                break;
                            case SQRT:
                                cadAux = "bltin SQRT";
                                name = "sqrt";
                                ptrFunc = "SQRT";
                                break;
                            case INTEGER:
                                cadAux = "bltin INTEGER";
                                name = "integer";
                                ptrFunc = "INTEGER";
                                break;
                        }
                        cadAux += "\n";
                        txtAreaTokens.append(cadAux);
                        break;
                    
                    case SYMBOL:
                        cadAux = "Symbol name: " + instruc.symbolHoc.name + " val=" + Float.toString(instruc.symbolHoc.val) + "\n";
                        txtAreaTokens.append(cadAux);
                        
                        switch(instruc.symbolHoc.TipoSymbol){
                            case VAR:
                                cadInst = "VAR";
                                name = instruc.symbolHoc.name;
                                valor = Float.toString(instruc.symbolHoc.val);
                                ptrFunc = "";
                                break;
                            case UNDEF:
                                cadInst = "UNDEF ";
                                name = instruc.symbolHoc.name;
                                valor = "---";
                                ptrFunc = "";
                                break;
                            case CONST_NUM:
                                cadInst = "CONST_NUM";
                                name = instruc.symbolHoc.name;
                                valor = Float.toString(instruc.symbolHoc.val);
                                ptrFunc = "";
                                break;
                            case CONST_PREDEF:
                                cadInst = "CONST_PREDEF";
                                name = instruc.symbolHoc.name;
                                valor = Float.toString(instruc.symbolHoc.val);
                                ptrFunc = "";
                                break;
                        }
                        break;
                        
                    case JUMP: 
                        cadInst = "JUMP"; 
                        valor = Integer.toString(instruc.jump);
                        break;
                    }
                    
                    os[0] = (Object)i;
                    os[1] = (Object)cadInst;
                    os[2] = (Object)name;
                    os[3] = (Object)valor;
                    os[4] = (Object)ptrFunc;
                    modeloTabla.addRow(os);
                }
        }catch(Exception ex){
            ex.printStackTrace();
        }
        
        txtResultSintactico.repaint();
        jTableCodigo.repaint();
    }//GEN-LAST:event_btnAnalizSintacticoActionPerformed

    private void ejecutarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejecutarCodigoActionPerformed
        // TODO add your handling code here:
        txtResultado.setText("");
        Sintac.maquinaHoc4.execute(0);
        Sintac.maquinaHoc4.AreaResult = txtResultado;
        txtResultado.repaint();
    }//GEN-LAST:event_ejecutarCodigoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formHoc5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formHoc5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formHoc5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formHoc5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formHoc5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalizSintactico;
    private javax.swing.JButton btnAnalizadorLex;
    private javax.swing.JButton ejecutarCodigo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableCodigo;
    private javax.swing.JTextArea textoAAnalizar;
    private javax.swing.JTextArea txtAreaTokens;
    public javax.swing.JTextArea txtResultSintactico;
    private javax.swing.JTextArea txtResultado;
    // End of variables declaration//GEN-END:variables
}
