/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CompiladoresHoc3;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.Reader;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java_cup.runtime.Symbol;

/**
 *
 * @author Jesus
 */
public class formHoc3 extends javax.swing.JFrame {
    AnalizadorSintactico Sintac;
    /**
     * Creates new form formHoc3
     */
    public formHoc3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textoAAnalizar = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaTokens = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtResultSintactico = new javax.swing.JTextArea();
        btnAnalizadorLex = new javax.swing.JButton();
        btnAnalizSintactico = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textoAAnalizar.setColumns(20);
        textoAAnalizar.setRows(5);
        jScrollPane1.setViewportView(textoAAnalizar);

        txtAreaTokens.setColumns(20);
        txtAreaTokens.setRows(5);
        jScrollPane2.setViewportView(txtAreaTokens);

        txtResultSintactico.setColumns(20);
        txtResultSintactico.setRows(5);
        jScrollPane3.setViewportView(txtResultSintactico);

        btnAnalizadorLex.setText("Analizar Léxicamente");
        btnAnalizadorLex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalizadorLexActionPerformed(evt);
            }
        });

        btnAnalizSintactico.setText("Sintáctico");

        jLabel1.setText("Expresión a Analizar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAnalizSintactico)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAnalizadorLex)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                                .addGap(31, 31, 31))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnalizadorLex)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(24, 24, 24)
                .addComponent(btnAnalizSintactico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnalizadorLexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalizadorLexActionPerformed
        // TODO add your handling code here:
        Symbol simb;
        String Lexema = new String();
        String cadAux = new String();
        File archEntrada = new File("archEntrada.txt");
        PrintWriter escribir;
        txtAreaTokens.setText("");
        
        try{
            escribir = new PrintWriter(archEntrada);
            escribir.print(textoAAnalizar.getText());
            escribir.close();
            //System.out.println("Obtiene texto a analizar");
        }catch(FileNotFoundException ex){
            //Logger.getLogger(formHoc3.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try{
            Reader lector;
            lector = new FileReader("archEntrada.txt");
            
            AnalizadorLexico AnalizLexico = new AnalizadorLexico(lector);
            //System.out.println("Lee aRCHENTRADA");
            do{
                simb = AnalizLexico.next_token();
                cadAux = Integer.toString(simb.sym);
                Lexema = AnalizLexico.yytext();
                
                if(simb.sym==AnalizadorSintacticoSym.EOF){
                    cadAux = "Token: " + cadAux + "\tIdentToken: FIN \n";
                }else{
                    switch(simb.sym){
                        case AnalizadorSintacticoSym.SEMIC:
                            cadAux = "Token: " + cadAux + "\tIdentToken: SEMIC\t Lexema: " + Lexema + "\n";
                            break;
                        case AnalizadorSintacticoSym.NUM:
                            cadAux = "Token: " + cadAux + "\tIdentToken: NUM\t Lexema: " + Lexema + "\n";
                            break;
                        case AnalizadorSintacticoSym.CONST_PRED:
                            cadAux = "Token: " + cadAux + "\tIdentToken: CONST_PRED\t Lexema: " + Lexema + "\n";
                            break;
                        case AnalizadorSintacticoSym.BLTIN:
                            cadAux = "Token: " + cadAux + "\tIdentToken: BLTIN\t Lexema: " + Lexema + "\n";
                            break;
                        case AnalizadorSintacticoSym.MENOSUNARIO:
                            cadAux = "Token: " + cadAux + "\tIdentToken: MENOSUNARIO\t Lexema: " + Lexema + "\n";
                            break;
                        case AnalizadorSintacticoSym.OpAsig:
                            cadAux = "Token: " + cadAux + "\tIdentToken: OpAsig\t Lexema: " + Lexema + "\n";
                            break;
                        case AnalizadorSintacticoSym.OpDiv:
                            cadAux = "Token: " + cadAux + "\tIdentToken: OpDiv\t Lexema: " + Lexema + "\n";
                            break;
                        case AnalizadorSintacticoSym.OpPotencia:
                            cadAux = "Token: " + cadAux + "\tIdentToken: OpPotencia\t Lexema: " + Lexema + "\n";
                            break;
                        case AnalizadorSintacticoSym.OpProd:
                            cadAux = "Token: " + cadAux + "\tIdentToken: OpProd\t Lexema: " + Lexema + "\n";
                            break;
                        case AnalizadorSintacticoSym.OpResta:
                            cadAux = "Token: " + cadAux + "\tIdentToken: OpResta\t Lexema: " + Lexema + "\n";
                            break;
                        case AnalizadorSintacticoSym.OpSuma:
                            cadAux = "Token: " + cadAux + "\tIdentToken: OpSuma\t Lexema: " + Lexema + "\n";
                            break;
                        case AnalizadorSintacticoSym.ParDer:
                            cadAux = "Token: " + cadAux + "\tIdentToken: ParDer\t Lexema: " + Lexema + "\n";
                            break;
                        case AnalizadorSintacticoSym.ParIzq:
                            cadAux = "Token: " + cadAux + "\tIdentToken: ParIzq\t Lexema: " + Lexema + "\n";
                            break;   
                        case AnalizadorSintacticoSym.VAR:
                            cadAux = "Token: " + cadAux + "\tIdentToken: VAR\t Lexema: " + Lexema + "\n";
                            break; 
                        default:
                            cadAux = "Token: " + cadAux + "\tIdentToken: OTRO\t Lexema: " + Lexema + "\n";
                    }
                }
                
                txtAreaTokens.append(cadAux);
                
            }while(simb.sym!=AnalizadorSintacticoSym.EOF);
        
        }catch(IOException ex){
            txtAreaTokens.append("CatchError \n");
            //Logger.getLogger(formHoc3.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        txtAreaTokens.repaint();
    }//GEN-LAST:event_btnAnalizadorLexActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formHoc3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formHoc3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formHoc3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formHoc3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formHoc3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalizSintactico;
    private javax.swing.JButton btnAnalizadorLex;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea textoAAnalizar;
    private javax.swing.JTextArea txtAreaTokens;
    public javax.swing.JTextArea txtResultSintactico;
    // End of variables declaration//GEN-END:variables
}
